### ISSUE TITLE
Can't fetch upstream

### ISSUE THREAD

**Issue by arm22** [uwcse440/web-cse440-sp16#32]
I am trying to add a new feature branch to add website updates.

`git remote -v`:

> origin https://github.com/arm22/web-cse440-sp16.git (fetch)
> origin https://github.com/arm22/web-cse440-sp16.git (push)
> upstream   git@github.com:uwcse440/web-cse440-sp16.git (fetch)
> upstream   git@github.com:uwcse440/web-cse440-sp16.git 

When I run `git fetch upstream`:

> Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights

**Comment by fiannaca** [comment]
It looks like you are using HTTPS but my instructions assumed you were using SSH. You should just need to update the remote URL for the upstream remote. Check out the instructions here: https://help.github.com/articles/changing-a-remote-s-url/

**Comment by fiannaca** [comment]
And you can go to the course repo to copy the correct HTTPS url instead of the SSH one

**Comment by fiannaca** [comment]
To get the hell, just click the "Clone or Download" button and then the use HTTPS link. It will then display the HTTPS URL for you to copy

**Comment by arm22** [comment]
Ah silly mistake. Working now. Thanks @fiannaca
